apiVersion: v1
kind: Namespace
metadata:
  name: vinylhound
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: vinylhound
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: vinylhound
